version: "3.2"

services:
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpass}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-pgdb}
    volumes:
      - db:/data/postgres
    ports:
      - "55432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db:
